<a href="https://colab.research.google.com/github/DianaShramchenko/data_mining/blob/main/%D0%BF%D1%801.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практическая работа №2. Библиотека Numpy

## Полезные материалы
- [Блокнот с полной теорией](https://colab.research.google.com/drive/1JlqwrIRsmnc9rW6Tj1XNgrtk--43dKvT?usp=sharing)
- [Блокнот с краткой теорией](https://colab.research.google.com/drive/1elIYEseXIidm5UUXnjgzWUehisw_OQ0w?usp=sharing)
- [Шпаргалка по numpy](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)
- [Numpy quick start](https://docs.scipy.org/doc/numpy/user/quickstart.html)
- [Datacamp numpy tutorial](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

## **Блок №1. Базовый уровень**

Установите зависимость с библиотекой NumPy:

In [1]:
import numpy as np

### **Задание №1. Создание массивов:**

а) Создайте одномерный массив из 10 нулей:


In [2]:
# 1V
zeros_array = np.zeros((1, 10))
print("\nV1:\n", zeros_array)

# 2V
zeros = np.full((1, 10), 0)
print("\nV2:\n", zeros)


V1:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

V2:
 [[0 0 0 0 0 0 0 0 0 0]]


б) Создайте двумерный массив с размерностью 5x5, заполненный единицами:

In [3]:
# 1V
one_array = np.ones((5, 5))
print("\nones:\n", one_array)
# 2V
one = np.full((5, 5), 1)
print("\nV2:\n", one)


ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

V2:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


в) Создайте массив с размерностью 3x3x3 со случайными значениями:

In [4]:
array = np.random.randint(1, 100, size=(3, 3, 3))
print("Массив случайных целых чисел:\n", array)

Массив случайных целых чисел:
 [[[66 76 69]
  [31 23 49]
  [37 27 89]]

 [[95 80 63]
  [41 85 56]
  [83 38 30]]

 [[20 13 86]
  [39 46 31]
  [76 44 72]]]


### **Задание №2. Индексация и срезы:**

а) Извлеките второй элемент из созданного одномерного массива нулей:

In [5]:
take_array = np.take(zeros, [1])
print(take_array)

[0]


б) Выберите вторую строку из двумерного массива единиц:

In [6]:
row_2 = one[1]
print("Вторая строка:\n", row_2)


Вторая строка:
 [1 1 1 1 1]


в) Получите первые два элемента каждой строки из двумерного массива единиц:

In [7]:
row_2_2 = one[:, :2]
print("Вторая строка:\n", row_2_2)

Вторая строка:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### **Задание №3. Операции над массивами:**

   а) Прибавьте 10 ко всем элементам одномерного массива нулей:


In [8]:
b_10 = np.array([10])
add = np.add(zeros, b_10)
print(add)

[[10 10 10 10 10 10 10 10 10 10]]


   б) Умножьте каждый элемент двумерного массива единиц на 3:


In [9]:
b_3 = np.array([3])
multiply = np.multiply(one, b_3)
print(multiply)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


   в) Вычислите сумму всех элементов в массиве 3x3x3 со случайными значениями:

In [10]:
sum = np.sum(array)
print(sum)

1465


### **Задание №4. Использование функций и методов NumPy:**


   а) Найдите максимальное и минимальное значения в массиве 3x3x3:


In [11]:
max = np.max(array)
min = np.min(array)
print("массив:\n", array)
print("максимальное значение:", max)
print("минимальное значение:", min)

массив:
 [[[66 76 69]
  [31 23 49]
  [37 27 89]]

 [[95 80 63]
  [41 85 56]
  [83 38 30]]

 [[20 13 86]
  [39 46 31]
  [76 44 72]]]
максимальное значение: 95
минимальное значение: 13


   б) Вычислите среднее значение всех элементов в одномерном массиве нулей после добавления к ним числа 10:


In [12]:
mean_val = np.mean(add)
print("Среднее значение:", mean_val)

Среднее значение: 10.0


   в) Используйте функцию `np.reshape` для изменения формы одномерного массива нулей в двумерный массив 2x5:

In [13]:
print("Исходный массив:", zeros)
reshaped_arr = np.reshape(zeros, (2, 5))
print("Массив после преобразования:\n", reshaped_arr)

Исходный массив: [[0 0 0 0 0 0 0 0 0 0]]
Массив после преобразования:
 [[0 0 0 0 0]
 [0 0 0 0 0]]


### **Задание №5. Логическая индексация:**

а) Создайте двумерный массив 4x4 со случайными целыми числами от 0 до 100. Затем выберите из этого массива все элементы, которые больше 70:

In [14]:
array_5 = np.random.randint(0, 101, size=(4, 4))
print("Массив случайных целых чисел:\n", array_5)
# Задаем критерий для фильтрации: выбираем элементы, которые больше 70
condition = array_5 > 70
# Применяем логическую индексацию для выбора элементов, удовлетворяющих условию
filtered_arr = array_5[condition]
print("Отфильтрованный массив (элементы > 70):\n", filtered_arr)

Массив случайных целых чисел:
 [[22 67 16 38]
 [74 93 10  7]
 [ 0 75 43 65]
 [91 63 32 39]]
Отфильтрованный массив (элементы > 70):
 [74 93 75 91]


б) Значения элементов, которые меньше 50, замените на 0:

In [15]:
array_5[array_5<50] = 0
print("Массив после замены элементов, которые меньше 50, на 0:\n", array_5)

Массив после замены элементов, которые меньше 50, на 0:
 [[ 0 67  0  0]
 [74 93  0  0]
 [ 0 75  0 65]
 [91 63  0  0]]


### **Задание №6. Линейная алгебра:**

   а) Создайте два массива размером 3x3 и выполните их матричное умножение:


In [16]:
a = np.random.randint(0, 31, size=(3, 3))
d = np.random.randint(0, 31, size=(3, 3))
m = np.dot(a, d)
print("массив 1:\n", a)
print("массив 2:\n",d)
print("матричное умножение:\n", m)

массив 1:
 [[17 23 21]
 [ 9  9 17]
 [24  1 27]]
массив 2:
 [[26  5 18]
 [ 0 24 17]
 [21 15 16]]
матричное умножение:
 [[ 883  952 1033]
 [ 591  516  587]
 [1191  549  881]]


   б) Найдите обратную матрицу для созданного двумерного массива 3x3:

In [17]:
inv_A = np.linalg.inv(m)
print("обратная матрица:\n", inv_A)

обратная матрица:
 [[-0.010227    0.02098949 -0.00199357]
 [-0.01379072  0.03496098 -0.00712404]
 [ 0.02241937 -0.05016125  0.00826952]]


## **Блок №2. Средний уровень**

### **Задание №1. Работа с многомерными массивами:**
   


а) Создайте трехмерный массив со случайными целыми числами и выполните транспонирование так, чтобы порядок осей стал обратным:

In [18]:
arr = np.random.randint(1, 100, size=(3, 3, 3))
print("Массив случайных целых чисел:\n", arr)
# Меняем местами оси
transposed = np.transpose(arr)
print("Транспонированный массив:\n", transposed)

Массив случайных целых чисел:
 [[[66  5 95]
  [17 99 44]
  [98 34 71]]

 [[22 71 47]
  [17 88 65]
  [14 87  3]]

 [[27 60 52]
  [ 5 58 22]
  [10 29  7]]]
Транспонированный массив:
 [[[66 22 27]
  [17 17  5]
  [98 14 10]]

 [[ 5 71 60]
  [99 88 58]
  [34 87 29]]

 [[95 47 52]
  [44 65 22]
  [71  3  7]]]


   б) Измените форму массива из предыдущего пункта так, чтобы получился двумерный массив (подумайте, как сохранить данные без потерь):

In [19]:
reshaped_transposed = np.reshape(transposed, (9, 3))
print("Массив после преобразования:\n", reshaped_transposed)

Массив после преобразования:
 [[66 22 27]
 [17 17  5]
 [98 14 10]
 [ 5 71 60]
 [99 88 58]
 [34 87 29]
 [95 47 52]
 [44 65 22]
 [71  3  7]]


```python
# Входные данные:
[
  [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
  ],
  [
    [13, 14, 15, 16],
    [17, 18, 19, 20],
    [21, 22, 23, 24]
  ]
]
```


```python
# Выходные данные:
[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12],
  [13, 14, 15, 16],
  [17, 18, 19, 20],
  [21, 22, 23, 24]
]
```


### **Задание №2. Маскирование и фильтрация:**
   а) Создайте массив со случайными целыми числами от -10 до 10. Затем, используя маскирование, замените все отрицательные числа на 0:


In [20]:
arr_2a = np.random.randint(-10, 11, size=(3, 4))
print("Массив случайных целых чисел:\n", arr_2a)
arr_2a[arr_2a < 0] = 0
print("Массив после замены элементов:\n", arr_2a)

Массив случайных целых чисел:
 [[ -8  -5 -10   6]
 [  5   7  -7  -9]
 [  9   3  -6   0]]
Массив после замены элементов:
 [[0 0 0 6]
 [5 7 0 0]
 [9 3 0 0]]


   б) Создайте двумерный массив и найдите значения, которые больше среднего значения по всему массиву, и замените их на 1:

In [21]:
arr_2b = np.random.randint(-10, 11, size=(3, 4))
print("Массив случайных целых чисел:\n", arr_2b)
mean_val_2b = np.mean(arr_2b)
arr_2b[arr_2b > mean_val_2b] = 1
print("Массив после замены элементов:\n", arr_2b)
print("среднее значение массива:", mean_val_2b)

Массив случайных целых чисел:
 [[-2 -9  5 -1]
 [-6 -8  2 -3]
 [ 8  1 -3  9]]
Массив после замены элементов:
 [[-2 -9  1 -1]
 [-6 -8  1 -3]
 [ 1  1 -3  1]]
среднее значение массива: -0.5833333333333334


### **Задание №3. Агрегирование данных:**


   а) Создайте двумерный массив со случайными числами. Вычислите сумму, среднее, максимум и минимум по столбцам и строкам:


In [22]:
arr_3a = np.random.randint(1, 31, size=(3, 3))
print("Массив случайных целых чисел:\n", arr_3a)

sum_rows = np.sum(arr_3a, axis=1)
sum_cols = np.sum(arr_3a, axis=0)
print("\nсумма по строкам\n", sum_rows)
print("\nсумма по столбцам\n", sum_cols)

mean_rows = np.mean(arr_3a, axis=1)
mean_cols = np.mean(arr_3a, axis=0)
print("\nсреднее по строкам\n", mean_rows)
print("\nсреднее по столбцам\n", mean_cols)

max_rows = np.max(arr_3a, axis=1)
max_cols = np.max(arr_3a, axis=0)
min_rows = np.min(arr_3a, axis=1)
min_cols = np.min(arr_3a, axis=0)
print("\nмаксимальное значение по строкам\n", max_rows)
print("\nмаксимальное значение по столбцам\n", max_cols)
print("\nминимальное значение по строкам\n", min_rows)
print("\nминимальное значение по столбцам\n", min_cols)


Массив случайных целых чисел:
 [[29 19 21]
 [ 8 22  6]
 [15 12 22]]

сумма по строкам
 [69 36 49]

сумма по столбцам
 [52 53 49]

среднее по строкам
 [23.         12.         16.33333333]

среднее по столбцам
 [17.33333333 17.66666667 16.33333333]

максимальное значение по строкам
 [29 22 22]

максимальное значение по столбцам
 [29 22 22]

минимальное значение по строкам
 [19  6 12]

минимальное значение по столбцам
 [ 8 12  6]


   б) Сгенерируйте массив случайных чисел и найдите дисперсию и стандартное отклонение:

In [23]:
arr_3b = np.random.randint(1, 31, size=(3, 3))
print("Массив случайных целых чисел:\n", arr_3b)
var_val = np.var(arr_3b)
print("Дисперсия:", var_val)
std_dev = np.std(arr_3b)
print("Стандартное отклонение:", std_dev)

Массив случайных целых чисел:
 [[29  1 22]
 [11  1 19]
 [16 11 11]]
Дисперсия: 75.58024691358024
Стандартное отклонение: 8.693690063119357


### **Задание №4. Использование функций для работы с матрицами:**

   а) Используйте функцию [`np.linalg.eig`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html#numpy.linalg.eig) для нахождения собственных значений и собственных векторов квадратной матрицы:

In [24]:
arr_4a = np.random.randint(1, 31, size=(2, 2))
print("квадратная матрица:\n", arr_4a)
eigenvalues, eigenvectors = np.linalg.eig(arr_4a)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

квадратная матрица:
 [[ 6  4]
 [13 19]]

Eigenvalues: [ 2.79175608 22.20824392]

Eigenvectors:
 [[-0.78008393 -0.23959951]
 [ 0.62567488 -0.97087181]]


   б) Решите систему линейных уравнений Ax = B, используя `np.linalg.solve`, где A и B — матрицы, заданные вами:

In [25]:
A = np.array([[1, 5], [6, 2]])
B = np.array([3, 5])
x = np.linalg.solve(A, B)
print("Решение Ax = b:", x)

Решение Ax = b: [0.67857143 0.46428571]


### **Задание №5. Работа с датасетом:**

   а) Загрузите датасет [**fetch california housing**](https://www.kaggle.com/datasets/harrywang/housing):

In [26]:
import numpy as np
from sklearn.datasets import fetch_california_housing

dataset = fetch_california_housing().data
dataset = np.asarray(dataset, np.float64)

б) Выведите первые 5 элементов датасета:

In [27]:
print(dataset[:5])

[[ 8.32520000e+00  4.10000000e+01  6.98412698e+00  1.02380952e+00
   3.22000000e+02  2.55555556e+00  3.78800000e+01 -1.22230000e+02]
 [ 8.30140000e+00  2.10000000e+01  6.23813708e+00  9.71880492e-01
   2.40100000e+03  2.10984183e+00  3.78600000e+01 -1.22220000e+02]
 [ 7.25740000e+00  5.20000000e+01  8.28813559e+00  1.07344633e+00
   4.96000000e+02  2.80225989e+00  3.78500000e+01 -1.22240000e+02]
 [ 5.64310000e+00  5.20000000e+01  5.81735160e+00  1.07305936e+00
   5.58000000e+02  2.54794521e+00  3.78500000e+01 -1.22250000e+02]
 [ 3.84620000e+00  5.20000000e+01  6.28185328e+00  1.08108108e+00
   5.65000000e+02  2.18146718e+00  3.78500000e+01 -1.22250000e+02]]


в) Выведите размерность датасета:

In [28]:
print("размерность массива:", dataset.shape)

размерность массива: (20640, 8)


г) Выведите общее количество элементов датасета:

In [29]:
print("Количество элементов:", dataset.size)

Количество элементов: 165120


д) Выведите тип данных элементов датасета:

In [30]:
print("Тип данных элементов массива:", dataset.dtype)

Тип данных элементов массива: float64


е) Выведите количество измерений (осей) датасета:

In [31]:
print("Количество измерений:", dataset.ndim)

Количество измерений: 2


ё) Выведите общее количество байт, занимаемых элементами датасета:

In [32]:
print("Общее количество байт:", dataset.nbytes)

Общее количество байт: 1320960


ж) Выведите размер одного элемента датасета в байтах:

In [33]:
print("Размер одного элемента в байтах:", dataset.itemsize)

Размер одного элемента в байтах: 8


 з) Выполните нормализацию данных в **столбцах**, приведя их к диапазону от 0 до 1, написав для этого отдельную функцию, реализующую алгоритм MinMaxScaler:

Алгоритм MinMaxScaler является методом масштабирования, который линейно преобразует данные так, чтобы они помещались в заданный диапазон, обычно между 0 и 1. Это достигается путем вычитания минимального значения признака из каждого значения, а затем деления разности на размах значений (максимальное значение минус минимальное значение). Преобразование можно выразить следующей формулой:

$X_{\text{scaled}} = \frac{X - X_{\min}}{X_{\max} - X_{\min}}$

Где:
- $X$ — исходное значение признака,
- $X_{\min}$ — минимальное значение этого признака в наборе данных,
- $X_{\max}$ — максимальное значение признака в наборе данных,
- $X_{\text{scaled}}$ — масштабированное значение признака.

Если требуется масштабировать данные в другой диапазон, например, $[a, b]$, то формула модифицируется:

$X_{\text{scaled}} = a + \frac{(X - X_{\min}) \times (b - a)}{X_{\max} - X_{\min}}$

In [34]:
def min_max_scaler(data):
    min = np.min(data, axis=0)
    max = np.max(data, axis=0)
    normalized = (data - min) / (max - min)
    return normalized
normalized_dataset = min_max_scaler(dataset)
print("Результаты нормализации:\n", normalized_dataset[:5])

Результаты нормализации:
 [[0.53966842 0.78431373 0.0435123  0.02046866 0.00894083 0.00149943
  0.5674814  0.21115538]
 [0.53802706 0.39215686 0.03822395 0.01892926 0.0672104  0.00114074
  0.565356   0.21215139]
 [0.46602805 1.         0.05275646 0.02194011 0.01381765 0.00169796
  0.5642933  0.21015936]
 [0.35469856 1.         0.03524099 0.02192864 0.01555537 0.0014933
  0.5642933  0.20916335]
 [0.23077613 1.         0.03853386 0.02216644 0.01575156 0.00119838
  0.5642933  0.20916335]]


   и) Используйте логическую индексацию для фильтрации данных по заданному условию (например, выберите все строки, где значение в определённом столбце превышает среднее значение этого столбца и выведите их значение):

In [35]:
# находим среднее значение в 4 столбце
mean = np.mean(dataset[:, 3])
# выбираем столбцы, в которых значения средних превышает ср. значение 4-го столбца
filtered = dataset[dataset[:, 3] > mean]

# Вывод отфильтрованных данных
print("Строки, где значение в первом столбце превышает среднее значение этого столбца:\n", filtered)

Строки, где значение в первом столбце превышает среднее значение этого столбца:
 [[   4.0368       52.            4.76165803 ...    2.13989637
    37.85       -122.25      ]
 [   2.0804       42.            4.29411765 ...    2.02689076
    37.84       -122.26      ]
 [   2.6736       52.            4.         ...    1.98275862
    37.84       -122.26      ]
 ...
 [   1.7          17.            5.20554273 ...    2.3256351
    39.43       -121.22      ]
 [   1.8672       18.            5.32951289 ...    2.12320917
    39.43       -121.32      ]
 [   2.3886       16.            5.25471698 ...    2.61698113
    39.37       -121.24      ]]


### **Задание №6. Работа с многомерными данными:**

Создайте двумерный массив и выполните "сглаживание" данных, заменив каждый элемент средним значением его и соседних элементов (по сторонам и по диагонали):



```
Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Smoothed Array:
[[3 3 4]
 [4 5 5]
 [6 6 7]]
```



In [36]:
arr_6 = np.random.randint(1, 6, size=(2, 2))
print("Исходный массив:\n", arr_6)


Исходный массив:
 [[3 3]
 [1 4]]
